# Generated by Django 3.2.12 on 2022-03-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atender',
            name='assunto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendidos', to='atendimento.assunto'),
        ),
        migrations.AlterField(
            model_name='atender',
            name='publico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendidos', to='atendimento.publico'),
        ),
        migrations.AlterField(
            model_name='atender',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendidos', to='atendimento.tipo'),
        ),
    ]
