# Generated by Django 3.2.12 on 2022-03-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_publico_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publico',
            name='nome',
        ),
        migrations.AddField(
            model_name='publico',
            name='assunto',
            field=models.ManyToManyField(to='atendimento.assunto'),
        ),
    ]
