# Generated by Django 3.2.12 on 2022-03-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_auto_20220317_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publico',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='publico',
            name='tipo',
        ),
    ]
