# Generated by Django 3.2.12 on 2022-03-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_atender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atender',
            name='assunto',
        ),
        migrations.AddField(
            model_name='atender',
            name='assunto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.assunto'),
        ),
        migrations.RemoveField(
            model_name='atender',
            name='publico',
        ),
        migrations.AddField(
            model_name='atender',
            name='publico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.publico'),
        ),
        migrations.RemoveField(
            model_name='atender',
            name='tipo',
        ),
        migrations.AddField(
            model_name='atender',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.tipo'),
        ),
    ]
